# Generated by Django 5.1.6 on 2025-02-22 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("founder", "founder"),
                            ("ceo", "ceo"),
                            ("cto", "cto"),
                            ("manager", "manager"),
                            ("frontend", "frontend"),
                            ("backend", "backend"),
                        ],
                        max_length=100,
                    ),
                ),
                ("has_children", models.BooleanField(default=False)),
                ("children_count", models.PositiveIntegerField(default=0)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="base.employee",
                    ),
                ),
            ],
        ),
    ]
